---
- hosts: all
  become: true
  tasks:
  - name: stop current running container
    command: docker stop poc-app-container
    ignore_errors: yes

  - name: remove stopped container
    command: docker rm poc-app-container
    ignore_errors: yes

  - name: remove docker image
    command: docker rmi mo1977/poc-devops-image:latest
    ignore_errors: yes

  - name: pull docker image from docker hub
    command: docker pull mo1977/poc-devops-image:latest
    ignore_errors: yes

  - name: creating container using mo1977/modify-tomcat-image
    command: docker run -d --name poc-app-container -p 8585:8080 mo1977/poc-devops-i                   mage:latest
